### ISSUE TITLE
Set $OPS_FORWARDS to a list of forwards defined in ops.yml before running action

### ISSUE THREAD

**Issue by rcgtnick** [nickthecook/crops#19]
Sometimes `ops.yml` exists to make it easy to forward actions to various directories from a single place, e.g. a user's home dir. For example, a VM with several ops-managed services installed on it in different directories.

To have an action execute something (e.g. `status`, `start`, etc.) for all defined forwards requires manually listing the forwards, like:

```yaml
forwards:
  app: /srv/app
  webui: /srv/webui
  proxy: https_proxy
actions:
  all:
    command: |
      for svc in $all_services; do
        ops -q $svc $*
      done
    param_expansion: true
options:
  environment:
    all_services: >-
      app
      webui
      proxy
```

 It would be nicer to be able to do something like this:

```yaml
forwards:
  app: /srv/app
  webui: /srv/webui
  proxy: https_proxy
actions:
  all:
    command: |
      for svc in $OPS_FORWARDS; do
        ops -q $svc $*
      done
    param_expansion: true
```

and not duplicate the list of forwards.
