### ISSUE TITLE
Hooks Not Running Before Forwards

### ISSUE THREAD

**Issue by tryton-oxaro** [nickthecook/crops#22]
With a hook that sets up environment specific state, a forwarded action can fail due to mismatched state when the hook doesn't run.

An example snippet of ops config and workflow that demonstrates the issue:

```yaml
hooks:
  before:
    - ln -sf config/$environment/backend.tf .
  forwards:
    prov: ansible
actions:
  ...
```

```sh
$ environment=foo ops <some-terraform-action>

$ environment=bar ops prov <action-that-depends-on-terraform>
Error: Backend initialization required: please run "terraform init"
# running in bar env but tried to use the foo tf backend
```

**Comment by nickthecook** [comment]
My concern with having hooks run when a forward is invoked is that there would be no easy way to run a forward without hooks. This could be a problem for other use cases.

For your case, you could define an action instead of a forward, like:

```yaml
hooks:
  before:
    - ln -sf config/$environment/backend.tf .
actions:
  prov: cd ansible && ops
```
